name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: Result of deployment step
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:  
  deploy:
    outputs:
      outcome: ${{ steps.set-set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output info
        run: echo "Deploying and uploading..."
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
